name: Publish on Nuget
on:
  push:
      branches: 
        - master

jobs:

  continuous-integration:

    runs-on: ubuntu-latest

    name: Build
    
    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Build
        run: |
          dotnet restore
          dotnet build
      - name: Test
        run: dotnet test

  continuous-deployment:

    needs: [continuous-integration]

    runs-on: ubuntu-latest
 
    name: Pack & publish
    
    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      - name: publish Essentials
        id: publish_nuget_essentials
        uses: rohith/publish-nuget@v2
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: src/AadvantageLab.Essentials/AadvantageLab.Essentials.csproj
          
          # NuGet package id, used for version detection & defaults to project name
          PACKAGE_NAME: AadvantageLab.Essentials

          # Regex pattern to extract version info in a capturing group
          VERSION_REGEX: <PackageVersion>(.*)<\/PackageVersion>

          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}