name: Consumer CI
on:
  push:
      branches: 
        - main
jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    name: Build
    env:
      BUILD_CONFIG: Release
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      
      - name: setup nuget
        uses: NuGet/setup-nuget@v1.0.5
        with:
          nuget-version: latest

      - name: Build
        run: |
          echo "Username: ${{ GITHUB_ACTOR }}"
          dotnet nuget add source https://nuget.pkg.github.com/jcl86/index.json -u ${{ GITHUB_ACTOR }} -n github -p ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
          dotnet restore src/SuperConsumer/SuperConsumer.csproj
          dotnet build src/SuperConsumer/SuperConsumer.csproj -c $BUILD_CONFIG