name: Publish on Github packages
on:
  push:
      branches: 
        - main
jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Build
        run: |
          dotnet restore
          dotnet build

  continuous-deployment:
    needs: [continuous-integration]
    runs-on: ubuntu-latest
    name: Pack & publish to github packages
    env:
      BUILD_CONFIG: Release

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      - name: dotnet build
        run: dotnet build github-packages.sln -c $BUILD_CONFIG
      - name: dotnet pack [SuperLibrary]
        run: dotnet pack ./src/SuperLibrary/SuperLibrary.csproj -c $BUILD_CONFIG -o ./artifacts

      - name: setup nuget
        uses: NuGet/setup-nuget@v1.0.5
        with:
          nuget-version: latest

      - name: Publish to Github packages
        run: |
          for f in ./artifacts/*.nupkg
          do
            echo "Publishing $f"
            curl --silent --show-error --fail -vX PUT -u "jcl86:${{ secrets.GITHUB_TOKEN }}" -F package=@$f https://nuget.pkg.github.com/jcl86/
            if [ $? -eq 0 ]
            then
              echo "successfully pushed $f"
            else
              echo "failed to push $f" >&2
              exit 1
            fi
          done
        shell: bash